version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore updates to NestJS packages that may break compatibility
      - "nestjs"
      - "nestjs/common"
      - "nestjs/core"
      - "nestjs/platform-express"
      - "nestjs/testing"
      - "nestjs/microservices"
      - "nestjs/websockets"
      # Ignore updates to packages with known vulnerabilities or compatibility issues
      - "lodash"
      - "rxjs"
      - "reflect-metadata"
      - "typeorm"
      - "bcrypt"
      - "jsonwebtoken"
